name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  test:
    name: Run All Tests
    uses: ./.github/workflows/ci.yml

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [test]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build project
      run: npm run build
    
    - name: Create tarball
      run: |
        npm pack
        mv *.tgz agent-communication-mcp.tgz
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          agent-communication-mcp.tgz
          dist/**/*
        generate_release_notes: true
        draft: false
        prerelease: ${{ contains(github.ref, '-beta') || contains(github.ref, '-alpha') }}
    
    - name: Publish to npm
      if: ${{ !contains(github.ref, '-beta') && !contains(github.ref, '-alpha') }}
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}